name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build ASP.NET Core app
        run: dotnet publish -c Release -o publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploy to Plesk via FTP
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: testcicd.bajarangdecorators.com
        run: |
          curl -T ./publish/* ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST/
